version: '3'

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      .env
    environment:
      - PYTHONUNBUFFERED=0
    expose:
      - "9000"
    ports:
      - "9000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pg-container/pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh
    ports:
      - "5432:5432"
    expose:
      - "5432"