# Generated by Django 2.2.10 on 2021-01-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True, verbose_name='Caminho')),
            ],
            options={
                'verbose_name_plural': 'Diretórios',
            },
        ),
        migrations.CreateModel(
            name='SubPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sub_path', models.CharField(blank=True, max_length=254, null=True, verbose_name='Caminho')),
            ],
            options={
                'verbose_name_plural': 'Sub Diretórios',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nome')),
                ('upload', models.FileField(blank=True, max_length=254, null=True, upload_to='', verbose_name='Arquivo')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Directories', verbose_name='Diretório')),
            ],
            options={
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.AddField(
            model_name='directories',
            name='sub_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.SubPath', verbose_name='Sub Diretório'),
        ),
    ]
